"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sample_users = exports.sample_tags = exports.sample_foods = void 0;
exports.sample_foods = [
    {
        id: "1",
        name: "Pizza carne",
        price: 35,
        tags: ["FastFood", "Pizza", "Lunch"],
        favorite: false,
        stars: 4.0,
        imageUrl: "assets/food-1.jpg",
        origins: ["Italy", "Rome"],
        cookTime: "40",
    },
    {
        id: "2",
        name: "Calzone",
        price: 20,
        tags: ["FastFood", "Snack"],
        favorite: true,
        stars: 5.0,
        imageUrl: "assets/food-2.jpg",
        origins: ["Italy", "Rome"],
        cookTime: "20",
    },
    {
        id: "3",
        name: "Lasagna",
        price: 25,
        tags: ["FastFood", "Lunch"],
        favorite: false,
        stars: 3.5,
        imageUrl: "assets/food-3.jpg",
        origins: ["Italy", "Rome"],
        cookTime: "30",
    },
    {
        id: "4",
        name: "Pizza Chicken",
        price: 35,
        tags: ["FastFood", "Pizza", "Lunch"],
        favorite: true,
        stars: 4.0,
        imageUrl: "assets/food-4.jpg",
        origins: ["Italy", "Rome"],
        cookTime: "40",
    },
    {
        id: "5",
        name: "Pizza Vegan",
        price: 30,
        tags: ["FastFood", "Pizza", "Vegan"],
        favorite: false,
        stars: 2.0,
        imageUrl: "assets/food-5.jpg",
        origins: ["Italy", "Rome"],
        cookTime: "40",
    },
    {
        id: "6",
        name: "Tiramisu",
        price: 20,
        tags: ["Desert"],
        favorite: true,
        stars: 4.5,
        imageUrl: "assets/food-6.jpg",
        origins: ["Italy", "Rome"],
        cookTime: "10",
    },
    {
        id: "7",
        name: "Pizza Quatro formaggi",
        price: 20,
        tags: ["Pizza"],
        favorite: true,
        stars: 4.5,
        imageUrl: "assets/quatro-formaggi.jpg",
        origins: ["Italy", "Rome"],
        cookTime: "10",
    },
    {
        id: "8",
        name: "Pizza Margherita",
        price: 20,
        tags: ["Pizza"],
        favorite: true,
        stars: 4.5,
        imageUrl: "assets/margherita.jpg",
        origins: ["Italy", "Rome"],
        cookTime: "10",
    },
    {
        id: "9",
        name: "Cheeseburger",
        price: 40,
        tags: ["Burger"],
        favorite: true,
        stars: 4.5,
        imageUrl: "assets/images/burgers/cheeseburger.jpg",
        origins: ["USA"],
        cookTime: "10",
    },
    {
        id: "10",
        name: "Burger Crispy",
        price: 40,
        tags: ["Burger"],
        favorite: true,
        stars: 4.5,
        imageUrl: "assets/images/burgers/crispy.jpg",
        origins: ["USA"],
        cookTime: "10",
    },
    {
        id: "11",
        name: "Burger Fish",
        price: 40,
        tags: ["Burger"],
        favorite: false,
        stars: 4,
        imageUrl: "assets/images/burgers/fish.jpg",
        origins: ["USA"],
        cookTime: "10",
    },
    {
        id: "12",
        name: "Burger Vegan",
        price: 40,
        tags: ["Burger"],
        favorite: false,
        stars: 3,
        imageUrl: "assets/images/burgers/vegan.jpg",
        origins: ["USA"],
        cookTime: "10",
    },
    {
        id: "13",
        name: "Cheesecake",
        price: 25,
        tags: ["Dessert"],
        favorite: false,
        stars: 4,
        imageUrl: "assets/images/dessert/cheesecake.jpg",
        origins: ["Italy"],
        cookTime: "10",
    },
    {
        id: "14",
        name: "Clatite cu ciocolata",
        price: 25,
        tags: ["Dessert"],
        favorite: false,
        stars: 4.5,
        imageUrl: "assets/images/dessert/clatite.jpg",
        origins: ["Romania"],
        cookTime: "10",
    },
    {
        id: "15",
        name: "Prajitura",
        price: 25,
        tags: ["Dessert"],
        favorite: false,
        stars: 5,
        imageUrl: "assets/images/dessert/prajitura.jpg",
        origins: ["Romania"],
        cookTime: "10",
    },
    {
        id: "16",
        name: "Pasta Bolognese",
        price: 35,
        tags: ["Pasta"],
        favorite: false,
        stars: 5,
        imageUrl: "assets/images/pasta/bolognese.jpg",
        origins: ["Italy"],
        cookTime: "30",
    },
    {
        id: "17",
        name: "Pasta Carbonara",
        price: 35,
        tags: ["Pasta"],
        favorite: false,
        stars: 5,
        imageUrl: "assets/images/pasta/carbonara.jpg",
        origins: ["Italy"],
        cookTime: "30",
    },
    {
        id: "18",
        name: "Pasta Con Pollo",
        price: 35,
        tags: ["Pasta"],
        favorite: true,
        stars: 5,
        imageUrl: "assets/images/pasta/con-pollo.jpg",
        origins: ["Italy"],
        cookTime: "30",
    },
    {
        id: "19",
        name: "Pasta Napoli",
        price: 35,
        tags: ["Pasta"],
        favorite: false,
        stars: 4,
        imageUrl: "assets/images/pasta/napoli.jpg",
        origins: ["Italy"],
        cookTime: "30",
    },
    {
        id: "20",
        name: "Pasta Ton",
        price: 3,
        tags: ["Pasta"],
        favorite: false,
        stars: 3,
        imageUrl: "assets/images/pasta/ton.jpg",
        origins: ["Italy"],
        cookTime: "30",
    },
];
exports.sample_tags = [
    { name: "All", count: 6 },
    { name: "FastFood", count: 3 },
    { name: "Pizza", count: 3 },
    { name: "Lunch", count: 3 },
    { name: "Snack", count: 1 },
    { name: "Vegan", count: 1 },
    { name: "Desert", count: 1 },
];
exports.sample_users = [
    {
        name: "Dragos",
        email: "dragos@gmail.com",
        password: "111",
        address: "iasi",
        isAdmin: true,
    },
    {
        name: "Stefania",
        email: "stefania@gmail.com",
        password: "222",
        address: "iasi",
        isAdmin: false,
    },
    {
        name: "Eduard",
        email: "eduard@gmail.com",
        password: "333",
        address: "iasi",
        isAdmin: false,
    },
    {
        name: "Paula",
        email: "paula@gmail.com",
        password: "444",
        address: "iasi",
        isAdmin: false,
    },
];
