import { Food } from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';
import { User } from './app/shared/models/User';

export const sample_foods: Food[] = [
  {
    id: '1',
    name: 'Pizza carne',
    locatie: 'Lacul Tarnita',
    data: '20 iunie 2024',
    ora: '12:00 - 17:00',
    price: 35,
    tags: ['FastFood', 'Pizza', 'Lunch'],
    imageUrl: 'assets/food-1.jpg',
    nrLocuri: '40',
  },
  {
    id: '2',
    name: 'Calzone',
    locatie: 'Lacul Tarnita',
    data: '20 iunie 2024',
    ora: '12:00 - 17:00',
    price: 20,
    tags: ['FastFood', 'Snack'],
    imageUrl: 'assets/food-2.jpg',
    nrLocuri: '20',
  },
  {
    id: '3',
    name: 'Lasagna',
    locatie: 'Lacul Tarnita',
    data: '20 iunie 2024',
    ora: '12:00 - 17:00',
    price: 25,
    tags: ['FastFood', 'Lunch'],
    imageUrl: 'assets/food-3.jpg',
    nrLocuri: '30',
  },
  {
    id: '4',
    name: 'Pizza Chicken',
    locatie: 'Lacul Tarnita',
    data: '20 iunie 2024',
    ora: '12:00 - 17:00',
    price: 35,
    tags: ['FastFood', 'Pizza', 'Lunch'],
    imageUrl: 'assets/food-4.jpg',
    nrLocuri: '40',
  },
  {
    id: '5',
    name: 'Pizza Vegan',
    locatie: 'Lacul Tarnita',
    data: '20 iunie 2024',
    ora: '12:00 - 17:00',
    price: 30,
    tags: ['FastFood', 'Pizza', 'Vegan'],
    imageUrl: 'assets/food-5.jpg',
    nrLocuri: '40',
  },
  {
    id: '6',
    name: 'Tiramisu',
    locatie: 'Lacul Tarnita',
    data: '20 iunie 2024',
    ora: '12:00 - 17:00',
    price: 20,
    tags: ['Desert'],
    imageUrl: 'assets/food-6.jpg',
    nrLocuri: '10',
  },
  {
    id: '7',
    name: 'Cheeseburger',
    locatie: 'Lacul Tarnita',
    data: '20 iunie 2024',
    ora: '12:00 - 17:00',
    price: 40,
    tags: ['Burger'],
    imageUrl: 'assets/images/burgers/cheeseburger.jpg',
    nrLocuri: '10',
  },
];

export const sample_tags: Tag[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 3 },
  { name: 'Pizza', count: 3 },
  { name: 'Lunch', count: 3 },
  { name: 'Snack', count: 1 },
  { name: 'Vegan', count: 1 },
  { name: 'Desert', count: 1 },
];

export const sample_users: any[] = [
  {
    name: 'Dragos',
    email: 'dragos@gmail.com',
    password: '111',
    address: 'iasi',
    isAdmin: true,
  },
  {
    name: 'Stefania',
    email: 'stefania@gmail.com',
    password: '222',
    address: 'iasi',
    isAdmin: false,
  },
  {
    name: 'Eduard',
    email: 'eduard@gmail.com',
    password: '333',
    address: 'iasi',
    isAdmin: false,
  },
  {
    name: 'Paula',
    email: 'paula@gmail.com',
    password: '444',
    address: 'iasi',
    isAdmin: false,
  },
];
